nginx:
    build: .
    dockerfile: Dockerfile.nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: .
    dockerfile: Dockerfile.appserver
    ports:
        - "5000"
node2:
    build: .
    dockerfile: Dockerfile.appserver
    ports:
        - "5000"
node3:
    build: .
    dockerfile: Dockerfile.appserver
    ports:
        - "5000"
